---
- import_tasks: preflight.yml

- name: fqdn | Configure Debian
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: fqdn | Configure Redhat
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Install loki
  ansible.builtin.include_tasks: loki.yml
  when: __install_loki

- name: Install promtail
  ansible.builtin.include_tasks: promtail.yml
  when:
    - __install_promtail
    - not promtail_use_docker

- name: Install promtail [Docker]
  ansible.builtin.include_tasks: promtail-docker.yml
  when:
    - __install_promtail
    - promtail_use_docker
